fix: update to node

diff --git a/.github/workflows/release-please.yml b/.github/workflows/release-please.yml
--- a/.github/workflows/release-please.yml
+++ b/.github/workflows/release-please.yml
@@ -42,7 +42,8 @@ jobs:
         run: |
           VERSION=$(echo "${{ steps.get-pr-data.outputs.pr-title }}" | grep -oP '(\d+\.\d+\.\d+)' || true)
           if [[ -z "$VERSION" ]]; then
-            echo "No version number found in PR title"
+            echo "::error::No version number found in PR title"
+            exit 1
           else
             MAJOR_MINOR_VERSION="${VERSION%.*}"
             PATCH_VERSION="${VERSION##*.}"
